# Generated by Django 5.0 on 2025-12-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='cleint',
            new_name='client',
        ),
    ]
